### ISSUE TITLE
Blank page appeared in the simulation

### ISSUE THREAD

**Issue by sravanthimodepu** [vlabs-on-openedx/open-edx-virtual-chemistry-lab-dei#1]
While testing the lab, found an issue that all the simulations are redirecting to an empty page.

**Comment by mrudhvika940** [comment]
Removed the following script which was repeated twice in all experiment's simulation html content

```
 var lab_id = "<lab_id>"; 
 var exp_name = "<exp_name>" 
 var lab_name = "<lab_name>" 
 var exp_id = "<exp_id>" 

```

**Comment by sravanthimodepu** [comment]
Simulations are loading slowly but are working properly. Hence closing the issue.
